Update patch set 1
Patch Set 1:

This needs to be verified by the multicloud team as there is no support for the wrapped being added:
jenkins_jobs.errors.JenkinsJobsException: Unknown entry point or macro 'golang114' for component type: 'wrapper'.

Patch-set: 1
CC: Gerrit User 481 <481@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>