Update patch set 4
Patch Set 4:

For some reason I started getting
" 
 ! [remote rejected]   HEAD -> refs/for/master (commit 9b82541: not Signed-off-by author/committer/uploader in message footer)
error: failed to push some refs to 'ssh://kaihlavi@gerrit.onap.org:29418/ci-management'
"
when trying to change this commit even though there should be nothing wrong with the sign-off?
I already tried starting from scratch once but still the same failure? Any ideas?

Patch-set: 4