Update patch set 2
Patch Set 2: Code-Review-1

See my comment in https://gerrit.onap.org/r/c/integration/+/104144/2 - as I already pointed out there this job template doesn't support subprojects, that's even what failed build logs tell you: 

jenkins_jobs.errors.JenkinsJobsException: Failed to find suitable template named '{project-name}-{stream}-{subproject}-verify-golang'

Patch-set: 2
Label: Code-Review=-1