Revert "[DCAE] Set 3.9 for tox run"
This reverts commit b39543603f98c745ece0f049644f6583a64d6195.

Reason for revert: 3.9 not supported under CI
ERROR: unknown environment 'py3.9' reported in logs

Change-Id: Iacfd5c3c9bcc64eeaebd0be73610e6347f3a0531
Signed-off-by: vv770d <vv770d@att.com>
Issue-ID: DCAEGEN2-3236