Update patch set 2
Patch Set 2:

Following /ci-management/Sandbox_Setup.md, I have a few problems when running sanbox.

1. after 
jenkins-jobs test jjb/ <job-name> -o <directoryname>
on 3 jobs, I got 3 folders

dl-clm:
total 24
drwxrwxr-x  2 osboxes osboxes 4096 Mar  6 20:36 ./
drwxrwxr-x 13 osboxes osboxes 4096 Mar  6 20:38 ../
-rw-rw-r--  1 osboxes osboxes 1147 Mar  6 20:36 01-Recent
-rw-rw-r--  1 osboxes osboxes  858 Mar  6 20:36 CLM
-rw-rw-r--  1 osboxes osboxes 1168 Mar  6 20:36 Daily-Jobs
-rw-rw-r--  1 osboxes osboxes 1171 Mar  6 20:36 External-Labs

dl-main:
total 24
drwxrwxr-x  2 osboxes osboxes 4096 Mar  6 20:38 ./
drwxrwxr-x 13 osboxes osboxes 4096 Mar  6 20:38 ../
-rw-rw-r--  1 osboxes osboxes 1147 Mar  6 20:38 01-Recent
-rw-rw-r--  1 osboxes osboxes  858 Mar  6 20:38 CLM
-rw-rw-r--  1 osboxes osboxes 1168 Mar  6 20:38 Daily-Jobs
-rw-rw-r--  1 osboxes osboxes 1171 Mar  6 20:38 External-Labs

dl-sonar:
total 60
drwxrwxr-x  2 osboxes osboxes  4096 Mar  6 19:44 ./
drwxrwxr-x 13 osboxes osboxes  4096 Mar  6 20:38 ../
-rw-rw-r--  1 osboxes osboxes  1147 Mar  6 19:44 01-Recent
-rw-rw-r--  1 osboxes osboxes   858 Mar  6 19:44 CLM
-rw-rw-r--  1 osboxes osboxes  1168 Mar  6 19:44 Daily-Jobs
-rw-rw-r--  1 osboxes osboxes 35317 Mar  6 19:44 dcaegen2-services-datalake-handler-sonar
-rw-rw-r--  1 osboxes osboxes  1171 Mar  6 19:44 External-Labs

Notice dl-sonar has an extra folder.

After submitting to sandbox, I only see one job on sanbox page:
dcaegen2-services-datalake-handler-sonar

After executing it, in its log, I found this error: (see https://logs.onap.org/sandbox/vex-yul-ecomp-jenkins-2/dcaegen2-services-datalake-handler-sonar/1/console.log.gz)

 > git fetch --tags --progress git://cloud.onap.org/mirror/dcaegen2/services/components/datalake-handler +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress git://cloud.onap.org/mirror/dcaegen2/services/components/datalake-handler +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: remote error: access denied or repository not exported: /mirror/dcaegen2/services/components/datalake-handler

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2042)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1761)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$400(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:442)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:655)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to snd-ubuntu1604-builder-4c-4g-68
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.GeneratedMethodAccessor792.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy107.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1152)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
		at hudson.scm.SCM.checkout(SCM.java:504)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
		at hudson.model.Run.execute(Run.java:1810)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
ERROR: Error cloning remote repo 'origin'
[FINDBUGS] Skipping publisher since build result is FAILURE

Basically 2 questions:
1. Why did I get one job submitted only?
2. What is the error in the log? Seems the sandbox can not connect to source code in gerrit.
 
The source code to test is in https://gerrit.onap.org/r/#/c/79055/

Patch-set: 2