Update patch set 1
Patch Set 1:

(1 comment)

I tried: jenkins-jobs test jjb/ oom-main-linters

but I have:
jenkins_jobs.errors.JenkinsJobsException: failure-notification parameter missing to format {failure-notification}

Patch-set: 1