Update patch set 2
Patch Set 2:

In vfc/vfc-nfvo-wfengine-java.yaml
What does this line mean? Does one need to define this 'settings'?
mvn-settings: 'vfc-nfvo-wfengine-settings'

Asked this because I saw this error in my log:
ERROR: not able to provide the file [ManagedFile: id=dcaegen2-services-datalake-handler-settings, targetLocation=, variable=SETTINGS_FILE], can't be resolved by any provider - maybe it got deleted by an administrator?

Patch-set: 2
Label: Code-Review=0