Update patch set 1
Patch Set 1:

here is the error:
jenkins_jobs.errors.JenkinsJobsException: pom parameter missing to format {pom}

Patch-set: 1
Label: Verified=0